### ISSUE TITLE
Change download folder doesn't have affect

### ISSUE THREAD

**Issue by PadseGaming** [shiningw/ncdownloader#47] opened 2022-04-05 11:30 UTC
Cant switch the download Path.

If u change the download folder to a specific path, downloads wont shown in this and are hidden on the cloud storage. 
After switching back to the app standard download path, surprise, all downloads will shown in this folder.

So ncdownloader cant handle other path's than the regular path which is used after install the app. No changes has affect. 

Hope to see a fix for it. :-) 

Greatz Paddy

**Comment by shiningw** [comment] 2022-04-17 02:08
Hi,
 this couldn't be reproduced in my installation. Anyone else has similar issues?

**Comment by shiningw** [comment] 2022-04-22 01:05
Thank you! By the way, I'm about to publish my fixes too and I'll merge yours. But have you verified that your fixes work with both internal NC local filesystem and external mounts? In my installation(21.07 and 23), filesystem::getLocalFolder fails to give me the correct real path.

I have to do something like this to get what I want if the folder is not within the nextcloud filesystem

`    public static function getLocalPath(string $path): ?string
    {
        $storage = Filesystem::getStorage($path);
        if ($storage) {
            $realpath = $storage->getLocalFile($path);
            $pos = strrpos($realpath,$path);
            return substr($realpath,0,$pos);
        }
        return null;
    }`

**Comment by polter-rnd** [comment] 2022-04-22 06:19
For me (NC 23) Filesystem::getLocalFolder works for both cases, I found this solution in ocDownloader repo. But maybe it's not the best one

When you will publish your fixes let me test on my installation before merge if possible, maybe there are some corner cases 🙂

**Comment by shiningw** [comment] 2022-04-22 10:35
I've got it wrong. Filesystem::getLocalFolder do works and my workaround is unwarranted! I've pushed my changes and you can take a look at it!

**Comment by polter-rnd** [comment] 2022-04-22 14:08
With your changes I have this error when downloading a file to external storage:

> Exception during scan: /Storage/Downloads#0 /var/www/html/custom_apps/ncdownloader/lib/Tools/folderScan.php(55): OC\\Files\\Utils\\Scanner->scan('/Storage/Downlo...')\n#1 /var/www/html/custom_apps/ncdownloader/lib/Tools/folderScan.php(46): OCA\\NCDownloader\\Tools\\folderScan->scan()\n#2 /var/www/html/custom_apps/ncdownloader/lib/Tools/folderScan.php(71): OCA\\NCDownloader\\Tools\\folderScan->update()\n#3 /var/www/html/custom_apps/ncdownloader/lib/Controller/Aria2Controller.php(149): OCA\\NCDownloader\\Tools\\folderScan::sync()\n#4 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(217): OCA\\NCDownloader\\Controller\\Aria2Controller->getStatus('active')\n#5 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(126): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\NCDownloader\\Controller\\Aria2Controller), 'getStatus')\n#6 /var/www/html/lib/private/AppFramework/App.php(157): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\NCDownloader\\Controller\\Aria2Controller), 'getStatus')\n#7 /var/www/html/lib/private/Route/Router.php(302): OC\\AppFramework\\App::main('Aria2Controller', 'getStatus', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#8 /var/www/html/lib/base.php(1006): OC\\Route\\Router->match('/apps/ncdownloa...')\n#9 /var/www/html/index.php(36): OC::handleRequest()\n#10 {main}

`/Storage` is an external storage mounted to different real directory.
With my change it works

Another problem is that when you open https://nextcloud.url/apps/ncdownloader/ without being logged in, you will got "Internal Server Error"
With my change it also works.

**Comment by shiningw** [comment] 2022-04-22 14:42
Hi,
 Can files be downloaded to the external dir correctly?
 The errors are a result of scanning the download dir too frequently and they are innocuous warnings. We can disable it by commenting it out in the folderScan class, or instead of scanning the directory whenever it has updated content, we can choose to do so only when a download finishes.  The second problem you mentioned is a bug that can be fixed easily! I should publish a fix later

**Comment by polter-rnd** [comment] 2022-04-22 15:03
Yep, they download correctly, also I see the progress is being updated in table. But this error is not about too frequent scaning, it's `NotFoundException`. And `/Storage/Downloads` is the wrong path, it should map to real path like `/external_storage/Downloads` in my case. So the path is incorrect - but why it is working? 🙂 What's the purpose of that scan?

**Comment by shiningw** [comment] 2022-04-22 15:15
Hi,
Are you saying that the file isn't downloaded to the correct folder?  Something could have gone awry. I tested it both nc21 and nc23 and it works as expected. folderScan is there to update the file entries in NC so files can be shown in your browser. Without it, files exists on your disk but won't be displayed in NC. the error is caused by this line https://github.com/shiningw/ncdownloader/blob/5ae16850447db9ae34f68a59002b568e8fbe6dce/lib/Tools/folderScan.php#L61

**Comment by polter-rnd** [comment] 2022-04-22 15:37
> Are you saying that the file isn't downloaded to the correct folder?

No, actually it is downloading to the right folder. So from the user side, everything works.

> folderScan is there to update the file entries in NC so files can be shown in your browser. Without it, files exists on your disk but won't be displayed in NC.

Yep, that's why it is interesting why I see that error with incorrect path in `folderScan` but at the same time entries are correctly updated. Looks that for some calls it takes the wrong path, but only for some corner cases.

Let me dig into it and I'll try to find what happens. I guess we should not see that error even if it downloads to the correct folder :slightly_smiling_face:

**Comment by polter-rnd** [comment] 2022-04-22 15:55
When I added this debug output to `folderScan::scan()`, I see every time it is being called with the wrong path, following that error:

```
diff --git a/lib/Tools/folderScan.php b/lib/Tools/folderScan.php
index ba3e9d3..bd0042b 100644
--- a/lib/Tools/folderScan.php
+++ b/lib/Tools/folderScan.php
@@ -51,6 +51,7 @@ class folderScan
     {
         $this->logger = \OC::$server->getLogger();
         $this->scanner = new Scanner($this->user, \OC::$server->getDatabaseConnection(), \OC::$server->query(IEventDispatcher::class), $this->logger);
+        Helper::debug("folderScan::scan() is called for user " . $this->user . ", path=" . $this->path);
         try {
             $this->scanner->scan($this->path);
             return ['status' => 'OK', 'path' => $this->path];
```

When I restart `aria2`, all entries in NC are gone. That's the reason of it?

**Comment by shiningw** [comment] 2022-04-22 15:55
Hi,
/Storage/Downloads is the correct argument that should be passed to OC\Files\Utils\Scanner::scan. You may as well take a look at the source code
https://github.com/nextcloud/server/blob/fb59875071ca260f97aaef4d8842a3f4140429de/lib/private/Files/Utils/Scanner.php#L194

**Comment by polter-rnd** [comment] 2022-04-22 15:56
> /Storage/Downloads is the correct argument that should be passed to OC\Files\Utils\Scanner::scan. You may as well take a look at the source code

Yep, I looked there, and seems that this error is from this exception:
```
			if (!$storage->file_exists($relativePath)) {
				throw new NotFoundException($dir);
			}
```

**Comment by shiningw** [comment] 2022-04-22 16:03
> When I added this debug output to `folderScan::scan()`, I see every time it is being called with the wrong path, following that error:
> 
> ```
> diff --git a/lib/Tools/folderScan.php b/lib/Tools/folderScan.php
> index ba3e9d3..bd0042b 100644
> --- a/lib/Tools/folderScan.php
> +++ b/lib/Tools/folderScan.php
> @@ -51,6 +51,7 @@ class folderScan
>      {
>          $this->logger = \OC::$server->getLogger();
>          $this->scanner = new Scanner($this->user, \OC::$server->getDatabaseConnection(), \OC::$server->query(IEventDispatcher::class), $this->logger);
> +        Helper::debug("folderScan::scan() is called for user " . $this->user . ", path=" . $this->path);
>          try {
>              $this->scanner->scan($this->path);
>              return ['status' => 'OK', 'path' => $this->path];
> ```
> 
> When I restart `aria2`, all entries in NC are gone. That's the reason of it?

Aria2 has nothing to do with this issue. Aria2 clears all session data when you shut it down. that's why all entries are gone. Correct me if I'm wrong

**Comment by polter-rnd** [comment] 2022-04-22 16:10
Yep, you're right, that was a wrong assumption from me. But I still can't understand how it works when every call to `scan()` ends with error. You've had incorrect error handling there, try this fix:

```
diff --git a/lib/Tools/folderScan.php b/lib/Tools/folderScan.php
index ba3e9d3..4b8e954 100644
--- a/lib/Tools/folderScan.php
+++ b/lib/Tools/folderScan.php
@@ -54,10 +54,11 @@ class folderScan
         try {
             $this->scanner->scan($this->path);
             return ['status' => 'OK', 'path' => $this->path];
-        } catch (ForbiddenException $e) {
+        } catch (\OCP\Files\ForbiddenException $e) {
             $this->logger->warning("Make sure you're running the scan command only as the user the web server runs as");
+        } catch (\OCP\Files\NotFoundException $e) {
+            $this->logger->warning("Path not found: " . $e->getMessage());
         } catch (\Exception $e) {
-
             $this->logger->warning("Exception during scan: " . $e->getMessage() . $e->getTraceAsString());
         }
         return ['status' => $e->getMessage(), 'path' => $this->path];
```

It will display `Path not found` every time for external resource

**Comment by shiningw** [comment] 2022-04-22 16:18
Hi,
I've published my latest changes and you can merge them with yours! Thank you!

**Comment by polter-rnd** [comment] 2022-04-22 19:06
Thanks! I've updated the PR. After the fix in error handling, you will see "Path for the scan command not found" for the each `folderScan::scan` call, and I have no idea why everything works at the same time :slightly_smiling_face:

**Comment by shiningw** [comment] 2022-04-24 08:17
Hi,
The issue is fixed in the latest release

**Closed by shiningw** 2022-04-24 08:17 UTC
